export type FarmType = 'crop' | 'dairy' | 'mixed';
export type LanguageCode = 'en' | 'kn' | 'hi' | 'te' | 'ta' | 'mr';

export interface LocationInfo {
  state: string;
  district: string;
  taluk?: string;
  village: string;
  pincode?: string;
}

export interface FarmerProfile {
  id: string;
  name: string;
  phoneNumber: string;
  email?: string;
  location: LocationInfo;
  farmType: FarmType;
  landAreaAcres: number;
  cattleCount: number;
  language: LanguageCode;
  onboarded: boolean;
}

// ---------------- FARM & PLOTS ----------------
export interface Farm {
  id: string;
  farmerId: string;
  name: string;
  surveyNumber?: string;
  village: string;
  totalAreaAcres: number;
  ownership: 'owned' | 'leased' | 'shared';
  createdAt: string;
}

export interface Plot {
  id: string;
  farmId: string;
  name: string;
  areaAcres: number;
  soilType: 'Red Loam' | 'Black Cotton' | 'Sandy Loam' | 'Clayey' | 'Alluvial';
  irrigationSource: 'Borewell' | 'Canal' | 'Drip Irrigation' | 'Rainfed' | 'Sprinkler';
  status: 'active' | 'fallow' | 'preparing';
}

// ---------------- AGRICULTURE & CROPS ----------------
export type CropStage = 'Land Prep' | 'Sowing' | 'Vegetative' | 'Flowering' | 'Maturity' | 'Harvesting' | 'Completed';

export interface CropCycle {
  id: string;
  plotId: string;
  farmerId: string;
  cropName: string;
  variety: string;
  season: 'Kharif' | 'Rabi' | 'Zaid';
  sowingDate: string;
  expectedHarvestDate: string;
  currentStage: CropStage;
  healthStatus: 'Excellent' | 'Good' | 'Needs Attention';
  estimatedYieldQuintals: number;
  actualHarvestQuintals?: number;
  status: 'active' | 'harvested' | 'failed';
}

export type ActivityType = 'Sowing' | 'Irrigation' | 'Fertilizer' | 'Pesticide' | 'Weeding' | 'Pruning' | 'Harvest' | 'Soil Test';

export interface CropActivity {
  id: string;
  cropCycleId: string;
  activityType: ActivityType;
  date: string;
  cost: number;
  inputUsed?: string;
  quantityUsed?: string;
  notes: string;
  loggedAt: string;
}

export interface DiseaseDetectionRecord {
  id: string;
  cropName: string;
  imageUrl?: string;
  detectedDisease: string;
  confidenceScore: number;
  severity: 'Low' | 'Medium' | 'High';
  recommendedActions: string[];
  isDemoInference: boolean;
  loggedAt: string;
}

export interface SoilHealthReport {
  id: string;
  plotId: string;
  sampleDate: string;
  ph: number;
  nitrogenKgPerHa: number;
  phosphorusKgPerHa: number;
  potassiumKgPerHa: number;
  organicCarbonPercent: number;
  soilHealthIndex: 'Optimal' | 'Medium' | 'Deficient';
  cropSuitability: string[];
  reportFileUrl?: string;
  fileName?: string;
  uploadedAt?: string;
  isLocalUpload?: boolean;
}

// ---------------- DAIRY & LIVESTOCK ----------------
export type LivestockType = 'Cow' | 'Buffalo' | 'Goat';

export interface Animal {
  id: string;
  tagNumber: string;
  name?: string;
  type: LivestockType;
  breed: string;
  ageYears: number;
  healthStatus: 'Healthy' | 'Under Treatment' | 'Quarantine' | 'Pregnant';
  milkingStatus: 'Milking' | 'Dry' | 'Heifer';
  dailyAverageYieldLiters: number;
  lastVaccinationDate?: string;
  pregnancyMonth?: number;
}

export interface MilkRecord {
  id: string;
  date: string;
  morningLiters: number;
  eveningLiters: number;
  totalLiters: number;
  avgFat: number;
  avgSnf: number;
  litersSold: number;
  litersRetained: number;
  ratePerLiter: number;
  totalRevenue: number;
  buyerName: string;
  isConfirmed: boolean;
  animalId?: string;
  notes?: string;
}

export interface HealthVaccinationRecord {
  id: string;
  animalId: string;
  tagNumber: string;
  recordType: 'Vaccination' | 'Deworming' | 'Treatment' | 'Veterinary Visit' | 'Calving';
  description: string;
  date: string;
  cost: number;
  nextDueDate?: string;
  vetName?: string;
}

export interface FeedRecord {
  id: string;
  feedName: string;
  quantityKg: number;
  costPerKg: number;
  totalCost: number;
  date: string;
  notes?: string;
}

// ---------------- FARM FINANCE ----------------
export type TransactionType = 'INCOME' | 'EXPENSE';
export type TransactionCategory = 
  | 'Milk Sale' 
  | 'Produce Sale' 
  | 'Fertilizer & Pesticide' 
  | 'Cattle Feed' 
  | 'Labor' 
  | 'Diesel & Power' 
  | 'Veterinary' 
  | 'Equipment Rental' 
  | 'Warehouse Rent' 
  | 'Government Subsidy' 
  | 'Other';

export interface FinancialTransaction {
  id: string;
  date: string;
  type: TransactionType;
  category: TransactionCategory;
  amount: number;
  relatedEntityId?: string; // Links to cropCycleId, milkRecordId, inventoryMovementId
  relatedEntityType?: 'crop' | 'dairy' | 'warehouse' | 'general';
  description: string;
  paymentMode: 'Cash' | 'UPI' | 'Bank Transfer' | 'Dairy MPCS Account';
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface FinancialSummary {
  totalIncome: number;
  totalExpense: number;
  netProfit: number;
  pendingReceivables: number;
  pendingPayables: number;
  cropProfit: number;
  dairyProfit: number;
}

// ---------------- WAREHOUSE & INVENTORY ----------------
export interface Warehouse {
  id: string;
  name: string;
  location: string;
  totalCapacityQuintals: number;
  usedCapacityQuintals: number;
  storageType: 'Dry Godown' | 'Cold Storage' | 'Silo' | 'Home Shed';
}

export interface InventoryItem {
  id: string;
  warehouseId: string;
  commodityName: string;
  variety: string;
  quantityQuintals: number;
  bagsCount: number;
  grade: 'A - Grade 1' | 'B - Fair Avg Quality' | 'C - Grade 2';
  entryDate: string;
  sourceType: 'Harvest' | 'Purchase' | 'Transfer';
  sourceId?: string;
}

export interface StockMovement {
  id: string;
  inventoryItemId: string;
  movementType: 'IN' | 'OUT';
  quantityQuintals: number;
  reason: 'Harvest Added' | 'Sold to Market' | 'Spoilage' | 'Seed Retention';
  referenceSaleId?: string;
  date: string;
  notes?: string;
}

// ---------------- MARKETPLACE & SUPPLY CHAIN ----------------
export interface MandiRate {
  id: string;
  mandiName: string;
  district: string;
  commodity: string;
  modalPricePerQuintal: number;
  minPrice: number;
  maxPrice: number;
  arrivalsMetricTon: number;
  updatedDate: string;
  isDemoData: boolean;
}

export interface MarketListing {
  id: string;
  sellerFarmerId: string;
  commodityName: string;
  variety: string;
  quantityQuintals: number;
  expectedPricePerQuintal: number;
  location: string;
  status: 'Active' | 'Under Negotiation' | 'Sold';
  sourceInventoryId?: string;
  createdAt: string;
}

export interface BuyerRequirement {
  id: string;
  buyerName: string;
  buyerType: 'APMC Trader' | 'FPO Aggregator' | 'Processor' | 'Retail Buyer';
  commodityName: string;
  targetQuantityQuintals: number;
  offeredPricePerQuintal: number;
  deliveryLocation: string;
  distanceKm: number;
  estimatedTransportCostPerQtl: number;
}

// ---------------- COMMUNITY ----------------
export interface CommunityPost {
  id: string;
  authorId: string;
  authorName: string;
  authorVillage: string;
  scope: 'state' | 'district' | 'all';
  category: 'Crops' | 'Dairy' | 'Govt Scheme' | 'Machinery' | 'Market Advice';
  content: string;
  likesCount: number;
  commentsCount: number;
  createdAt: string;
  hasLiked?: boolean;
}

export interface PostComment {
  id: string;
  postId: string;
  authorName: string;
  content: string;
  createdAt: string;
}

// ---------------- TASKS & NOTIFICATIONS ----------------
export interface FarmTask {
  id: string;
  title: string;
  category: 'crop' | 'dairy' | 'finance' | 'warehouse' | 'general';
  dueTime: string;
  priority: 'high' | 'medium' | 'low';
  completed: boolean;
  sourceModule?: string;
  createdAt: string;
}

// ---------------- AI ASSISTANT ----------------
export interface AIChatMessage {
  id: string;
  sender: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  toolCall?: {
    toolName: string;
    parameters: Record<string, any>;
    status: 'pending_confirmation' | 'executed' | 'cancelled';
  };
}

// Backward compatible aliases
export type CropSummary = CropCycle;
export type DailyMilkSummary = MilkRecord;
export type DailyTask = FarmTask;
export type FinancialMetric = {
  todayIncome: number;
  todayExpense: number;
  monthlyProfit: number;
  pendingReceivables: number;
};
