'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { 
  ArrowLeft, 
  IndianRupee, 
  Plus, 
  ArrowUpRight, 
  ArrowDownLeft, 
  Calendar,
  Filter,
  X,
  TrendingUp,
  Tag
} from 'lucide-react';
import { useFarmer } from '@/context/FarmerContext';
import { BottomNav } from '@/components/layout/BottomNav';
import { FinancialTransaction } from '@/types';

export default function FinancePage() {
  const { transactions, financialSummary, addTransaction, showToast } = useFarmer();
  const [activeTab, setActiveTab] = useState<'overview' | 'income' | 'expense'>('overview');

  // Modal State for adding transaction
  const [showTxModal, setShowTxModal] = useState(false);
  const [modalType, setModalType] = useState<'INCOME' | 'EXPENSE'>('INCOME');

  // Form State
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState<any>('Produce Sale');
  const [txDate, setTxDate] = useState(new Date().toISOString().split('T')[0]);
  const [description, setDescription] = useState('');
  const [paymentMode, setPaymentMode] = useState<'Cash' | 'UPI' | 'Bank Transfer'>('UPI');
  const [entityType, setEntityType] = useState<'crop' | 'dairy' | 'warehouse' | 'general'>('crop');
  const [formError, setFormError] = useState('');

  // Category filter for sub-tabs
  const [selectedFilterCategory, setSelectedFilterCategory] = useState<string>('all');

  const incomeCategories = ['Produce Sale', 'Milk Sale', 'Government Subsidy', 'Other'];
  const expenseCategories = ['Cattle Feed', 'Fertilizer & Pesticide', 'Labor', 'Diesel & Power', 'Veterinary', 'Equipment Rental', 'Warehouse Rent', 'Other'];

  const openAddModal = (type: 'INCOME' | 'EXPENSE') => {
    setModalType(type);
    setCategory(type === 'INCOME' ? 'Produce Sale' : 'Cattle Feed');
    setEntityType(type === 'INCOME' ? 'crop' : 'dairy');
    setAmount('');
    setDescription('');
    setFormError('');
    setShowTxModal(true);
  };

  const handleTxSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError('');

    const parsedAmount = parseFloat(amount);
    if (isNaN(parsedAmount) || parsedAmount <= 0) {
      setFormError('Please enter a valid amount greater than ₹0.');
      return;
    }
    if (!description.trim()) {
      setFormError('Please enter a short description/source.');
      return;
    }

    addTransaction({
      date: txDate,
      type: modalType,
      category,
      amount: parsedAmount,
      description: description.trim(),
      paymentMode,
      relatedEntityType: entityType,
      isAutoGenerated: false,
    });

    setShowTxModal(false);
  };

  const incomeTransactions = transactions.filter(t => t.type === 'INCOME');
  const expenseTransactions = transactions.filter(t => t.type === 'EXPENSE');

  const filteredIncomes = selectedFilterCategory === 'all' 
    ? incomeTransactions 
    : incomeTransactions.filter(t => t.category === selectedFilterCategory);

  const filteredExpenses = selectedFilterCategory === 'all' 
    ? expenseTransactions 
    : expenseTransactions.filter(t => t.category === selectedFilterCategory);

  // Exact real math from actual stored records
  const realTotalIncome = incomeTransactions.reduce((acc, t) => acc + t.amount, 0);
  const realTotalExpense = expenseTransactions.reduce((acc, t) => acc + t.amount, 0);
  const realNetProfit = realTotalIncome - realTotalExpense;

  const cropIncomeTotal = incomeTransactions.filter(t => t.relatedEntityType === 'crop' || t.category === 'Produce Sale').reduce((acc, t) => acc + t.amount, 0);
  const dairyIncomeTotal = incomeTransactions.filter(t => t.relatedEntityType === 'dairy' || t.category === 'Milk Sale').reduce((acc, t) => acc + t.amount, 0);

  const milkPercent = realTotalIncome > 0 ? Math.round((dairyIncomeTotal / realTotalIncome) * 100) : 50;
  const cropPercent = realTotalIncome > 0 ? Math.round((cropIncomeTotal / realTotalIncome) * 100) : 40;
  const otherPercent = Math.max(0, 100 - milkPercent - cropPercent);

  return (
    <div className="flex-1 flex flex-col bg-[#F7F9F6] text-stone-900 pb-20">
      
      {/* HEADER */}
      <header className="bg-emerald-700 text-white px-4 py-3 flex items-center justify-between shadow-sm">
        <div className="flex items-center gap-2">
          <Link href="/" className="p-1 rounded-lg hover:bg-emerald-800">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-base font-black">Farm Finance Ledger</h1>
        </div>

        <button 
          onClick={() => openAddModal(activeTab === 'expense' ? 'EXPENSE' : 'INCOME')}
          className="text-xs font-bold bg-white text-emerald-800 px-3 py-1.5 rounded-xl shadow-2xs hover:bg-emerald-50 active:scale-95 transition-all flex items-center gap-1"
        >
          <Plus className="w-3.5 h-3.5" />
          <span>{activeTab === 'expense' ? 'Add Expense' : 'Add Entry'}</span>
        </button>
      </header>

      {/* BODY CONTENT */}
      <div className="p-3.5 space-y-3.5">
        
        {/* SUB-TABS (Overview, Income, Expenses) */}
        <div className="flex items-center gap-1.5 p-1 bg-white border border-stone-200 rounded-2xl text-xs font-bold">
          <button 
            onClick={() => { setActiveTab('overview'); setSelectedFilterCategory('all'); }}
            className={`flex-1 py-1.5 rounded-xl transition-all ${activeTab === 'overview' ? 'bg-emerald-700 text-white shadow-2xs' : 'text-stone-500'}`}
          >
            Overview
          </button>
          <button 
            onClick={() => { setActiveTab('income'); setSelectedFilterCategory('all'); }}
            className={`flex-1 py-1.5 rounded-xl transition-all ${activeTab === 'income' ? 'bg-emerald-700 text-white shadow-2xs' : 'text-stone-500'}`}
          >
            Income ({incomeTransactions.length})
          </button>
          <button 
            onClick={() => { setActiveTab('expense'); setSelectedFilterCategory('all'); }}
            className={`flex-1 py-1.5 rounded-xl transition-all ${activeTab === 'expense' ? 'bg-emerald-700 text-white shadow-2xs' : 'text-stone-500'}`}
          >
            Expenses ({expenseTransactions.length})
          </button>
        </div>

        {/* ================= VIEW 1: OVERVIEW ================= */}
        {activeTab === 'overview' && (
          <div className="space-y-3.5">
            
            {/* Net Balance Card */}
            <div className="bg-white p-4 rounded-2xl border border-stone-200 shadow-2xs space-y-3">
              <div className="flex justify-between items-start">
                <div>
                  <p className="text-[10px] text-stone-400 font-bold uppercase tracking-wider">Net Farm Balance (Profit)</p>
                  <h2 className={`text-2xl font-black mt-0.5 ${realNetProfit >= 0 ? 'text-emerald-700' : 'text-rose-600'}`}>
                    ₹ {realNetProfit.toLocaleString('en-IN')}
                  </h2>
                </div>
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full border ${
                  realNetProfit >= 0 ? 'text-emerald-700 bg-emerald-50 border-emerald-200' : 'text-rose-700 bg-rose-50 border-rose-200'
                }`}>
                  {realNetProfit >= 0 ? 'Positive Net Margin' : 'Deficit'}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3 pt-2 border-t border-stone-100">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 rounded-lg bg-emerald-50 text-emerald-600">
                    <ArrowDownLeft className="w-4 h-4" />
                  </div>
                  <div>
                    <p className="text-[10px] text-stone-400 font-medium">Total Income</p>
                    <p className="text-sm font-bold text-stone-900">₹ {realTotalIncome.toLocaleString('en-IN')}</p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <div className="p-1.5 rounded-lg bg-rose-50 text-rose-600">
                    <ArrowUpRight className="w-4 h-4" />
                  </div>
                  <div>
                    <p className="text-[10px] text-stone-400 font-medium">Total Expenses</p>
                    <p className="text-sm font-bold text-stone-900">₹ {realTotalExpense.toLocaleString('en-IN')}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Income Streams Breakdown */}
            <div className="bg-white p-3.5 rounded-2xl border border-stone-200 shadow-2xs space-y-3">
              <h3 className="text-xs font-bold text-stone-700 uppercase tracking-wider">Revenue Breakdown</h3>

              <div className="space-y-2">
                <div>
                  <div className="flex justify-between text-xs font-semibold text-stone-700 mb-1">
                    <span>Dairy & Milk Sales (₹{dairyIncomeTotal})</span>
                    <span className="font-bold text-sky-800">{milkPercent}%</span>
                  </div>
                  <div className="h-2 w-full bg-stone-100 rounded-full overflow-hidden">
                    <div className="h-full bg-sky-600 rounded-full" style={{ width: `${milkPercent}%` }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold text-stone-700 mb-1">
                    <span>Crops & Produce Sales (₹{cropIncomeTotal})</span>
                    <span className="font-bold text-emerald-800">{cropPercent}%</span>
                  </div>
                  <div className="h-2 w-full bg-stone-100 rounded-full overflow-hidden">
                    <div className="h-full bg-emerald-600 rounded-full" style={{ width: `${cropPercent}%` }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold text-stone-700 mb-1">
                    <span>Subsidies & Other</span>
                    <span className="font-bold text-amber-800">{otherPercent}%</span>
                  </div>
                  <div className="h-2 w-full bg-stone-100 rounded-full overflow-hidden">
                    <div className="h-full bg-amber-600 rounded-full" style={{ width: `${otherPercent}%` }} />
                  </div>
                </div>
              </div>
            </div>

            {/* Recent 5 Transactions */}
            <div className="space-y-2">
              <div className="flex justify-between items-center text-xs font-bold text-stone-500 uppercase">
                <span>Recent Transactions</span>
                <span className="text-[10px] text-stone-400">{transactions.length} Total</span>
              </div>

              {transactions.slice(0, 5).map((tx) => (
                <div key={tx.id} className="p-3 bg-white rounded-xl border border-stone-200 flex justify-between items-center text-xs shadow-2xs">
                  <div>
                    <p className="font-bold text-stone-900">{tx.description || tx.category}</p>
                    <p className="text-[10px] text-stone-400">
                      {tx.date} • {tx.paymentMode} • <span className="font-medium text-stone-600">{tx.category}</span>
                    </p>
                  </div>
                  <span className={`font-black text-sm ${tx.type === 'INCOME' ? 'text-emerald-700' : 'text-stone-800'}`}>
                    {tx.type === 'INCOME' ? '+' : '-'}₹ {tx.amount.toLocaleString('en-IN')}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ================= VIEW 2: DEDICATED INCOME VIEW ================= */}
        {activeTab === 'income' && (
          <div className="space-y-3">
            
            {/* Income Total Summary */}
            <div className="bg-emerald-800 text-white p-4 rounded-2xl shadow-sm flex items-center justify-between">
              <div>
                <p className="text-xs text-emerald-200 font-semibold uppercase">Total Income Recorded</p>
                <h2 className="text-2xl font-black mt-0.5">₹ {realTotalIncome.toLocaleString('en-IN')}</h2>
                <p className="text-[11px] text-emerald-200 mt-1">From crops, milk, and subsidies</p>
              </div>
              <button 
                onClick={() => openAddModal('INCOME')}
                className="px-3 py-2 bg-white text-emerald-900 font-bold rounded-xl text-xs shrink-0 shadow-2xs flex items-center gap-1 active:scale-95"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>+ Add Income</span>
              </button>
            </div>

            {/* Filter Pills */}
            <div className="flex gap-1.5 overflow-x-auto pb-1 text-xs">
              <button
                onClick={() => setSelectedFilterCategory('all')}
                className={`px-3 py-1 rounded-xl font-bold whitespace-nowrap transition-all ${
                  selectedFilterCategory === 'all' ? 'bg-emerald-700 text-white' : 'bg-white text-stone-600 border border-stone-200'
                }`}
              >
                All Income ({incomeTransactions.length})
              </button>
              {incomeCategories.map(cat => (
                <button
                  key={cat}
                  onClick={() => setSelectedFilterCategory(cat)}
                  className={`px-3 py-1 rounded-xl font-bold whitespace-nowrap transition-all ${
                    selectedFilterCategory === cat ? 'bg-emerald-700 text-white' : 'bg-white text-stone-600 border border-stone-200'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>

            {/* Income Transactions List */}
            <div className="space-y-2">
              {filteredIncomes.length === 0 ? (
                <div className="p-8 text-center bg-white rounded-2xl border border-stone-200 text-stone-400 text-xs">
                  No income transactions found in this category.
                </div>
              ) : (
                filteredIncomes.map((tx) => (
                  <div key={tx.id} className="p-3 bg-white rounded-xl border border-stone-200 flex justify-between items-center text-xs shadow-2xs">
                    <div className="flex items-center gap-2.5">
                      <div className="p-2 rounded-xl bg-emerald-50 text-emerald-700">
                        <ArrowDownLeft className="w-4 h-4" />
                      </div>
                      <div>
                        <p className="font-bold text-stone-900">{tx.description}</p>
                        <p className="text-[10px] text-stone-400">
                          {tx.date} • {tx.paymentMode} • <span className="text-emerald-800 font-semibold">{tx.category}</span>
                        </p>
                      </div>
                    </div>
                    <span className="font-black text-sm text-emerald-700">
                      +₹ {tx.amount.toLocaleString('en-IN')}
                    </span>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

        {/* ================= VIEW 3: DEDICATED EXPENSES VIEW ================= */}
        {activeTab === 'expense' && (
          <div className="space-y-3">
            
            {/* Expense Total Summary */}
            <div className="bg-stone-800 text-white p-4 rounded-2xl shadow-sm flex items-center justify-between">
              <div>
                <p className="text-xs text-stone-400 font-semibold uppercase">Total Expenses Recorded</p>
                <h2 className="text-2xl font-black mt-0.5">₹ {realTotalExpense.toLocaleString('en-IN')}</h2>
                <p className="text-[11px] text-stone-400 mt-1">Cattle feed, fertilizer, labour &amp; inputs</p>
              </div>
              <button 
                onClick={() => openAddModal('EXPENSE')}
                className="px-3 py-2 bg-rose-600 text-white font-bold rounded-xl text-xs shrink-0 shadow-2xs flex items-center gap-1 active:scale-95"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>+ Add Expense</span>
              </button>
            </div>

            {/* Filter Pills */}
            <div className="flex gap-1.5 overflow-x-auto pb-1 text-xs">
              <button
                onClick={() => setSelectedFilterCategory('all')}
                className={`px-3 py-1 rounded-xl font-bold whitespace-nowrap transition-all ${
                  selectedFilterCategory === 'all' ? 'bg-stone-800 text-white' : 'bg-white text-stone-600 border border-stone-200'
                }`}
              >
                All Expenses ({expenseTransactions.length})
              </button>
              {expenseCategories.map(cat => (
                <button
                  key={cat}
                  onClick={() => setSelectedFilterCategory(cat)}
                  className={`px-3 py-1 rounded-xl font-bold whitespace-nowrap transition-all ${
                    selectedFilterCategory === cat ? 'bg-stone-800 text-white' : 'bg-white text-stone-600 border border-stone-200'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>

            {/* Expense Transactions List */}
            <div className="space-y-2">
              {filteredExpenses.length === 0 ? (
                <div className="p-8 text-center bg-white rounded-2xl border border-stone-200 text-stone-400 text-xs">
                  No expense transactions found in this category.
                </div>
              ) : (
                filteredExpenses.map((tx) => (
                  <div key={tx.id} className="p-3 bg-white rounded-xl border border-stone-200 flex justify-between items-center text-xs shadow-2xs">
                    <div className="flex items-center gap-2.5">
                      <div className="p-2 rounded-xl bg-rose-50 text-rose-600">
                        <ArrowUpRight className="w-4 h-4" />
                      </div>
                      <div>
                        <p className="font-bold text-stone-900">{tx.description}</p>
                        <p className="text-[10px] text-stone-400">
                          {tx.date} • {tx.paymentMode} • <span className="text-stone-700 font-semibold">{tx.category}</span>
                        </p>
                      </div>
                    </div>
                    <span className="font-black text-sm text-stone-900">
                      -₹ {tx.amount.toLocaleString('en-IN')}
                    </span>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

      </div>

      {/* ================= MODAL: ADD INCOME / EXPENSE TRANSACTION ================= */}
      {showTxModal && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl p-5 w-full max-w-sm shadow-2xl animate-in zoom-in-95">
            <div className="flex justify-between items-center mb-3">
              <h2 className="font-black text-base text-stone-900">
                {modalType === 'INCOME' ? 'Add Income Record' : 'Add Expense Record'}
              </h2>
              <button onClick={() => setShowTxModal(false)} className="p-1 rounded-lg text-stone-400 hover:text-stone-700">
                <X className="w-4 h-4" />
              </button>
            </div>

            {formError && (
              <div className="p-2.5 mb-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-medium">
                {formError}
              </div>
            )}

            <form onSubmit={handleTxSubmit} className="space-y-3">
              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Amount (₹) *</label>
                <input
                  type="number"
                  placeholder="e.g. 1500"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  className="w-full h-11 px-3 bg-stone-50 rounded-xl border border-stone-200 text-base font-black text-stone-900"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Category *</label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="w-full h-11 px-3 bg-stone-50 rounded-xl border border-stone-200 text-xs font-bold"
                >
                  {modalType === 'INCOME' ? (
                    incomeCategories.map(cat => <option key={cat} value={cat}>{cat}</option>)
                  ) : (
                    expenseCategories.map(cat => <option key={cat} value={cat}>{cat}</option>)
                  )}
                </select>
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Description / Source *</label>
                <input
                  type="text"
                  placeholder={modalType === 'INCOME' ? "e.g. Sold 5 bags Tomato at Sandur APMC" : "e.g. Bought 2 bags Cattle Feed from dealer"}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full h-11 px-3 bg-stone-50 rounded-xl border border-stone-200 text-xs font-medium"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">Date *</label>
                  <input
                    type="date"
                    value={txDate}
                    onChange={(e) => setTxDate(e.target.value)}
                    className="w-full h-11 px-2.5 bg-stone-50 rounded-xl border border-stone-200 text-xs font-bold"
                    required
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">Payment Mode</label>
                  <select
                    value={paymentMode}
                    onChange={(e) => setPaymentMode(e.target.value as any)}
                    className="w-full h-11 px-2 bg-stone-50 rounded-xl border border-stone-200 text-xs font-bold"
                  >
                    <option value="UPI">UPI / GPay</option>
                    <option value="Cash">Cash</option>
                    <option value="Bank Transfer">Bank Transfer</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">Related Enterprise</label>
                <select
                  value={entityType}
                  onChange={(e) => setEntityType(e.target.value as any)}
                  className="w-full h-11 px-3 bg-stone-50 rounded-xl border border-stone-200 text-xs font-bold"
                >
                  <option value="crop">Crops / Agriculture</option>
                  <option value="dairy">Dairy / Livestock</option>
                  <option value="other">General Farm</option>
                </select>
              </div>

              <div className="flex gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowTxModal(false)}
                  className="flex-1 h-11 rounded-xl border border-stone-300 font-bold text-xs text-stone-700 hover:bg-stone-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className={`flex-1 h-11 text-white font-bold text-xs rounded-xl shadow-md active:scale-95 transition-all ${
                    modalType === 'INCOME' ? 'bg-emerald-700 hover:bg-emerald-800' : 'bg-rose-600 hover:bg-rose-700'
                  }`}
                >
                  Save Transaction
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      <BottomNav />
    </div>
  );
}
